#image:
#  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: install  
    init: echo 'init script 1' # runs during prebuild
    command: |
      sudo apt update
      sudo apt install -y fonts-firacode mc binwalk clang tmux 

  - name: install 2  
    init: echo 'init script 1' # runs during prebuild
    command: |
      sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  - name: run script   
    init: echo 'init script' # runs during prebuild
    command: |
      npm start



# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 9222
    onOpen: open-preview
